import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) { 
  return ( 
    <html lang="en"> 
      <body> 
        <header> 
          <h1>My Next.js Training App</h1> 
        </header> 
        <Navigation /> 
        <main style={{ border: "2px solid gray", padding: "15px" }}> 
  {children} 
    </main> 
        <footer> 
          <p>© 2025 My App</p> 
        </footer> 
      </body> 
    </html> 
  ); 
} 